name: Build bundle

on:
    # This workflow is triggered on a schedule and manually via workflow_dispatch.
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          fetch-depth: 0

      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Build bundle
        run: node scripts/build-bundle.mjs --push

      - name: Push changes
        run: git push origin main
        if: always()
